import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildSchema, validate, parse, print } from "graphql";

import * as publicDocs from "./queries";
import * as adminDocs from "./admin-queries";
import * as legacyDocs from "./legacy-queries";

/**
 * Validates every GraphQL document the frontend sends against the schema the
 * API actually serves.
 *
 * This exists because the entire admin detail/mutation surface was broken for
 * a month: the documents declared `$id: String!` while every admin field takes
 * `id: ID!`. GraphQL rejects that statically, so `/admin/organizations/[id]`,
 * `/admin/users/[id]`, suspend, promote, delete and the check controls all
 * failed with "Variable $id of type String! used in position expecting type
 * ID!". Nothing caught it, because no test ever compared the two sides — the
 * frontend tests mock Apollo, and the API tests never see these documents.
 *
 * The schema files are generated by Nest on boot (`autoSchemaFile`) and are
 * committed, so this is a real cross-project contract check rather than a
 * snapshot of the frontend against itself.
 */
const SCHEMAS = {
  public: resolve(__dirname, "../../api/src/schema.gql"),
  admin: resolve(__dirname, "../../api/src/admin-schema.gql"),
} as const;

/** Pull every exported gql document out of a module. */
function documentsOf(mod: Record<string, unknown>): [string, string][] {
  return Object.entries(mod)
    .filter(([, v]) => typeof v === "object" && v !== null && "kind" in v)
    .map(([name, doc]) => [name, print(doc as Parameters<typeof print>[0])]);
}

describe.each([
  ["public", SCHEMAS.public, publicDocs] as const,
  ["admin", SCHEMAS.admin, adminDocs] as const,
  ["legacy public", SCHEMAS.public, legacyDocs] as const,
])("%s GraphQL documents match the served schema", (_surface, schemaPath, mod) => {
  const schema = buildSchema(readFileSync(schemaPath, "utf8"));
  const documents = documentsOf(mod as Record<string, unknown>);

  it("exports at least one document", () => {
    expect(documents.length).toBeGreaterThan(0);
  });

  it.each(documents)("%s validates", (_name, source) => {
    const errors = validate(schema, parse(source));
    expect(errors.map((e) => e.message)).toEqual([]);
  });
});

const CANONICAL_WORKSPACE_DOCUMENTS = [
  "CHECKS",
  "CREATE_CHECK",
  "CREATE_ACTIVE_CHECK",
  "CHANNELS",
  "CREATE_CHANNEL",
  "STATUS_PAGES",
  "CREATE_STATUS_PAGE",
] as const;

const CANONICAL_TOKEN_DOCUMENTS = [
  "CREATE_API_TOKEN",
  "API_TOKENS",
] as const;

const CANONICAL_TOKEN_SOURCE_FILES = [
  ["queries", resolve(__dirname, "queries.ts")],
  [
    "agent connections page",
    resolve(__dirname, "../app/(app)/account/agent-connections/page.tsx"),
  ],
  [
    "agent connections fixtures",
    resolve(__dirname, "../app/(app)/account/agent-connections/page.test.tsx"),
  ],
  [
    "connect agent fixtures",
    resolve(__dirname, "../components/app/connect-agent-dialog.test.tsx"),
  ],
] as const;

describe("canonical workspace GraphQL documents", () => {
  it.each(CANONICAL_WORKSPACE_DOCUMENTS)(
    "%s is organization-scoped without a project selector",
    (name) => {
      const source = print(publicDocs[name]);
      expect(source).toContain("$organizationId: ID!");
      expect(source).toContain("organizationId: $organizationId");
      expect(source).not.toContain("projectId");
    },
  );

  it("keeps project-slug lookup only in the legacy document module", () => {
    expect(legacyDocs).toHaveProperty("CHECK_BY_SLUG");
    expect(print(legacyDocs.CHECK_BY_SLUG)).toContain("projectSlug");
    expect(publicDocs).not.toHaveProperty("CHECK_BY_SLUG");
  });
});

describe("canonical API token GraphQL surface", () => {
  it.each(CANONICAL_TOKEN_DOCUMENTS)(
    "%s does not select a legacy project ID",
    (name) => {
      expect(print(publicDocs[name])).not.toContain("projectId");
    },
  );

  it.each(CANONICAL_TOKEN_SOURCE_FILES)(
    "%s contains no canonical projectId type or fixture",
    (_name, path) => {
      expect(readFileSync(path, "utf8")).not.toContain("projectId");
    },
  );
});
