import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildSchema, validate, parse, print } from "graphql";

import * as publicDocs from "./queries";
import * as adminDocs from "./admin-queries";

/**
 * Validates every GraphQL document the frontend sends against the schema the
 * API actually serves.
 *
 * This exists because the entire admin detail/mutation surface was broken for
 * a month: the documents declared `$id: String!` while every admin field takes
 * `id: ID!`. GraphQL rejects that statically, so `/admin/organizations/[id]`,
 * `/admin/users/[id]`, suspend, promote, delete and the check controls all
 * failed with "Variable $id of type String! used in position expecting type
 * ID!". Nothing caught it, because no test ever compared the two sides — the
 * frontend tests mock Apollo, and the API tests never see these documents.
 *
 * The schema files are generated by Nest on boot (`autoSchemaFile`) and are
 * committed, so this is a real cross-project contract check rather than a
 * snapshot of the frontend against itself.
 */
const SCHEMAS = {
  public: resolve(__dirname, "../../api/src/schema.gql"),
  admin: resolve(__dirname, "../../api/src/admin-schema.gql"),
} as const;

/** Pull every exported gql document out of a module. */
function documentsOf(mod: Record<string, unknown>): [string, string][] {
  return Object.entries(mod)
    .filter(([, v]) => typeof v === "object" && v !== null && "kind" in v)
    .map(([name, doc]) => [name, print(doc as Parameters<typeof print>[0])]);
}

describe.each([
  ["public", SCHEMAS.public, publicDocs] as const,
  ["admin", SCHEMAS.admin, adminDocs] as const,
])("%s GraphQL documents match the served schema", (_surface, schemaPath, mod) => {
  const schema = buildSchema(readFileSync(schemaPath, "utf8"));
  const documents = documentsOf(mod as Record<string, unknown>);

  it("exports at least one document", () => {
    expect(documents.length).toBeGreaterThan(0);
  });

  it.each(documents)("%s validates", (_name, source) => {
    const errors = validate(schema, parse(source));
    expect(errors.map((e) => e.message)).toEqual([]);
  });
});
